InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: wix
Installers:
- AppsAndFeaturesEntries:
  - DisplayName: DockerInWSL 1.5.184.230524
    UpgradeCode: '{A7DFAA38-00C1-4187-9F41-D6C11A8955D5}'
  Architecture: x64
  InstallerSha256: 613362C7DBB3B6C44D4FCD940D8CD62F793B7F1DF3BF027A0C878A25C848F0CE
  InstallerUrl: https://github.com/cloudflightio/dockerinwsl/releases/download/v1.5.184/DockerInWSL_1.5.184.230524.msi
  ProductCode: '{B1BC6B39-9D03-4F1E-829B-042244A999AD}'
ManifestType: installer
ManifestVersion: 1.4.0
MinimumOSVersion: 10.0.0.0
PackageIdentifier: Cloudflight.DockerInWSL
PackageVersion: 1.5.184.230524
Scope: machine
UpgradeBehavior: install
