InstallModes:
- silent
- silentWithProgress
InstallerLocale: en-US
InstallerType: wix
Installers:
- AppsAndFeaturesEntries:
  - DisplayName: DockerInWSL 1.4.150.230420
    UpgradeCode: '{A7DFAA38-00C1-4187-9F41-D6C11A8955D5}'
  Architecture: x64
  InstallerSha256: 348775CCC71166831DEBAE2094683A1F6F71DB53FAE1E56B799698D5B720187C
  InstallerUrl: https://github.com/cloudflightio/dockerinwsl/releases/download/v1.4.150/DockerInWSL_1.4.150.230420.msi
  ProductCode: '{AA39D2BC-F684-49D9-84A1-85C5DA6301A7}'
ManifestType: installer
ManifestVersion: 1.4.0
MinimumOSVersion: 10.0.0.0
PackageIdentifier: Cloudflight.DockerInWSL
PackageVersion: 1.4.150.230420
Scope: machine
UpgradeBehavior: install
